# Generated by Django 5.1 on 2026-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Executive Director', max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('signature', models.ImageField(blank=True, upload_to='team/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CEO Message',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class e.g. fa-heart', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
